name: 'create-localization-issue'
description: 'Create an issue when new localization data is available'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  base-dir:
    description: 'Directory containing localization files'
    required: false
    default: 'assets/base/assets/localization'
  base-file:
    description: 'Native translation file'
    required: false
    default: 'en.json'
  branch:
    description: 'Branch to operate on'
    required: false
    default: 'main'
  commit:
    description: 'Old commit to check against. Defaults to last'
    required: false
    default: 'HEAD^'
  maintainers:
    description: 'Path to maintainers JSON file'
    required: false
    default: 'localization_maintainers.json'
  template:
    description: 'Path to YAML markdown template'
    required: false
    default: '/scripts/template.yml'
outputs:
  issue-title:
    description: 'Generated title'
  issue-body:
    description: 'Generated localization diff body'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --base_dir
    - ${{ inputs.base-dir }}
    - --base_file
    -  ${{ inputs.base-file }}
    - --branch
    -  ${{ inputs.branch }}
    - --commit
    -  ${{ inputs.commit }}
    - --maintainers
    -  ${{ inputs.maintainers }}
    - --template
    -  ${{ inputs.template }}
