name: 'create-localization-issue'
description: 'Create an issue when new localization data is available'
branding:
  icon: 'flag-checkered'
  color: 'green'

inputs:
  base-dir:
    description: 'Directory containing localization files'
    required: false
    default: 'assets/base/assets/localization'
  base-file:
    description: 'Native translation file'
    required: false
    default: 'en.json'
  branch:
    description: 'Branch to operate on'
    required: false
    default: 'main'
  commit:
    description: 'Old commit to check against. Defaults to last'
    required: false
    default: 'HEAD^'
  maintainers:
    description: 'Path to maintainers JSON file'
    required: false
    default: 'localization_maintainers.json'
  template:
    description: 'Path to YAML markdown template'
    required: false
    default: '/scripts/template.yml'
  disable-mentions:
    description: 'Output mentions as Text (without @)'
    required: false
    type: choice
    options:
    - 'True'
    - 'False'
    default: 'False'
  js-patch:
    description: 'use git diff for JSON templates (for large repos)'
    required: false
    type: choice
    options:
    - 'True'
    - 'False'
    default: 'False'
  use-comments:
    description: 'Show templates as comments'
    required: false
    type: choice
    options:
    - 'True'
    - 'False'
    default: 'False'
  GITHUB_TOKEN:
    description: 'Token'
    required: true
    default: 'False'
  sub-ref:
    description: 'Token'
    required: true
  labels:
    description: 'Issue, labels'
    required: false
    default: 'localization, automated, help wanted'
outputs:
  issue-title:
    description: 'Generated title'
  issue-body:
    description: 'Generated localization diff body'
  comments:
    description: 'List of issue comments'

runs:
  using: "composite"
  steps:
    - name: mkdir
      shell: bash
      run: |
        mkdir comments

    - name: Run Python action (local)
      id: run_action
      uses: Knutschbert/create-localization-issue/.github/actions/docker-action-folder@v0
      with:
        base-dir: ${{ inputs.base-dir }} 
        base-file: ${{ inputs.base-file }}
        branch: ${{ inputs.branch }}
        commit: ${{ inputs.commit }}
        maintainers: ${{ inputs.maintainers }}
        template: ${{ inputs.template }}
        disable-mentions: ${{ inputs.disable-mentions }}
        js-patch: ${{ inputs.js-patch }}
        use-comments: ${{ inputs.use-comments }}
        labels: ${{ inputs.labels }}


    - name: Create GitHub issue
      id: create_issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        title: ${{ steps.run_action.outputs.issue-title }}
        body: ${{ steps.run_action.outputs.issue-body }}
        labels: |
          ${{ inputs.labels }}

    - name: List comments
      if: ${{ inputs.use-comments == 'True' }}
      shell: bash
      run: |
        ls -l comments/*.*
          
    - name: Post issue comments from markdown files
      if: ${{ inputs.use-comments == 'True' }}
      shell: bash
      env:
        ISSUE_NUMBER: ${{ steps.create_issue.outputs.number }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        for file in comments/*.md; do
          gh api repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            --method POST \
            --header "Authorization: Bearer $GITHUB_TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            --raw-field body="$(< "$file")"
        done
