name: 'create-localization-issue'
description: 'Create an issue when new localization data is available'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  base-dir:
    description: 'Directory containing localization files'
    required: false
    default: 'assets/base/assets/localization'
  base-file:
    description: 'Native translation file'
    required: false
    default: 'en.json'
  branch:
    description: 'Branch to operate on'
    required: false
    default: 'main'
  commit:
    description: 'Old commit to check against. Defaults to last'
    required: false
    default: 'HEAD^'
  maintainers:
    description: 'Path to maintainers JSON file'
    required: false
    default: 'localization_maintainers.json'
  template:
    description: 'Path to YAML markdown template'
    required: false
    default: '/scripts/template.yml'
  disable-mentions:
    description: 'Output mentions as Text (without @)'
    required: false
    type: choice
    options:
    - 'True'
    - 'False'
    default: 'False'
  js-patch:
    description: 'use git diff for JSON templates (for large repos)'
    required: false
    type: choice
    options:
    - 'True'
    - 'False'
    default: 'False'
  use-comments:
    description: 'Show templates as comments'
    required: false
    type: choice
    options:
    - 'True'
    - 'False'
    default: 'False'
outputs:
  issue-title:
    description: 'Generated title'
  issue-body:
    description: 'Generated localization diff body'
  comments:
    description: 'List of issue comments'
runs:
  using: 'docker'
  image: './../../../Dockerfile'
  args:
    - --base_dir
    - ${{ inputs.base-dir }}
    - --base_file
    -  ${{ inputs.base-file }}
    - --branch
    -  ${{ inputs.branch }}
    - --commit
    -  ${{ inputs.commit }}
    - --maintainers
    -  ${{ inputs.maintainers }}
    - --template
    -  ${{ inputs.template }}
    - --disable_mentions
    -  ${{ inputs.disable-mentions }}
    - --js_patch
    -  ${{ inputs.js-patch }}
    - --use_comments
    -  ${{ inputs.use-comments }}