name: (Installer) Create Localization Help Issue

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to compare to (last by default)'
        type: string
        default: '9405b236240511f3df1f2475cda04ca16450e36b'
        required: true
      template:
        description: 'Custom YAML template for Markdown (if needed)'
        type: string
        default: '/scripts/template.yml'
        required: true
      disable-mentions:
        description: 'Print mentions as string'
        type: choice
        options: [ 'True', 'False' ]
        default: 'False'
        required: true
      js-patch:
        description: 'Show JSON templates as diff'
        required: true
        type: choice
        options: [ 'True', 'False' ]
        default: 'False'
      use-comments:
        description: 'Show templates as comments'
        required: true
        type: choice
        options: [ 'True', 'False' ]
        default: 'True'
      labels:
        description: 'Issue, labels'
        required: false
        default: 'localization, automated, help wanted'

jobs:
  create-localization-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: examples

      - name: Run Python Action from external repo
        id: run_action
        uses: Knutschbert/create-localization-issue@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          base-dir: "assets/ue4ss_installer_gui"
          base-file: "en.json"
          branch: examples
          commit: ${{ github.event.inputs.commit }}
          maintainers: "translators_installer.json"
          template: ${{ github.event.inputs.template }}
          disable-mentions: ${{ github.event.inputs.disable-mentions }}
          js-patch: ${{ github.event.inputs.js-patch }}
          use-comments: ${{ github.event.inputs.use-comments }}
          labels: ${{ github.event.inputs.labels }}